export const UPDATE_OLD_EXPR_STRING = "UPDATE_OLD_EXPR_STRING";
export const UPDATE_NEW_EXPR_STRING = "UPDATE_NEW_EXPR_STRING";
export const UPDATE_UID = "UPDATE_UID";
export const UPDATE_DISPLAY_TREE_CHECK_MARKS = "UPDATE_DISPLAY_TREE_CHECK_MARKS";
export const UPDATE_MY_FILES = "UPDATE_MY_FILES";
export const UPDATE_OTHER_FILES = "UPDATE_OTHER_FILES";